name: My Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name : Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
  build-api-app:
    needs: build
    runs-on: windows-latest
    steps:
      - run: echo Hello, windows!

  packaging:
    needs: [build, build-api-app]
    runs-on: macos-latest
    steps:
      - run: echo Hello, macos!

  build-db:
    runs-on: windows-latest
    steps:
      - run: echo Hello, windows!